version: '2.2'
services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@s92xg47l4b23gw8g_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=db_user_sales
      - spring.datasource.password=Oraclecloud123
    restart: always